#!/bin/sh

# only need to change this line for different tests
# by specifying name of test (which is also the name
# of the directory containing the test)
export SYSTEST=VerticalGamma100MeV

# script that invokes this one needs to run this from test directory
source ../../../cmt/setup.sh

# make sure Gleam uses local job options file
../../../Linux-i686/Gleam.exe ${GLEAMROOT}/src/systests/${SYSTEST}/jobOptions.txt

# RUN_linux root macro contains boilerplate calls for 
# generating root histograms from Gleam output 
root -b -q RUN_linux

mv Histograms.root ${SYSTEST}Histos.root

rm mc.root digi.root recon.root